"""Practice memory service — session context management and long-term memory.

Three-layer memory model:
  1. 用户画像 (user profile)   → generated by app/services/user_profile.py
  2. 当前会话 (current session) → recent messages within the active session
  3. 长期记忆 (long-term memory) → key insights persisted across sessions
"""

from __future__ import annotations

import hashlib
from typing import Any

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.practice_session import LongTermMemory, PracticeMessage


async def get_session_context(
    session: AsyncSession,
    session_id: int,
    max_turns: int = 10,
) -> list[dict[str, Any]]:
    """Retrieve recent messages from the current practice session.

    Returns the most recent N turns as a list of {role, content} dicts
    suitable for injection into the LLM messages array.
    """
    result = await session.execute(
        select(PracticeMessage)
        .where(PracticeMessage.session_id == session_id)
        .order_by(PracticeMessage.turn_number.desc(), PracticeMessage.id.desc())
        .limit(max_turns * 3)  # ~3 messages per turn (user + assistant + tool)
    )
    messages = result.scalars().all()
    # Reverse to chronological order
    messages = list(reversed(messages))

    context: list[dict[str, Any]] = []
    for msg in messages:
        entry: dict[str, Any] = {"role": msg.role}
        if msg.content:
            entry["content"] = msg.content
        if msg.tool_calls:
            entry["tool_calls"] = msg.tool_calls
        if msg.tool_results:
            entry["tool_results"] = msg.tool_results
        if msg.evaluation:
            entry["evaluation"] = msg.evaluation
        context.append(entry)
    return context


def _make_memory_key(user_id: int, memory_type: str, content_hash: str) -> str:
    """Generate a unique, stable memory key for deduplication."""
    return f"u{user_id}:{memory_type}:{content_hash}"


def _content_hash(text: str, length: int = 16) -> str:
    """Short hash of text content for deduplication keys."""
    return hashlib.md5(text.encode("utf-8")).hexdigest()[:length]


async def retrieve_memories(
    session: AsyncSession,
    user_id: int,
    query_hints: list[str] | None = None,
    top_k: int = 5,
    min_importance: int = 3,
) -> list[dict[str, Any]]:
    """Retrieve relevant long-term memories for the current context.

    Memories are ranked by importance (desc), then recall_count (desc).
    When query_hints are provided, we also match against memory_key keywords.
    """
    stmt = (
        select(LongTermMemory)
        .where(
            LongTermMemory.user_id == user_id,
            LongTermMemory.importance >= min_importance,
        )
        .order_by(
            LongTermMemory.importance.desc(),
            LongTermMemory.recall_count.desc(),
        )
        .limit(max(20, top_k * 3))  # Fetch more, filter by hints below
    )

    result = await session.execute(stmt)
    memories = result.scalars().all()

    scored: list[tuple[int, LongTermMemory]] = []
    hints_lower = [h.lower() for h in (query_hints or [])]

    for m in memories:
        score = m.importance
        if hints_lower:
            key_lower = m.memory_key.lower()
            val_lower = m.memory_value.lower()
            for hint in hints_lower:
                if hint in key_lower or hint in val_lower:
                    score += 5  # Boost relevance
        scored.append((score, m))

    # Sort by score desc, then recall_count desc
    scored.sort(key=lambda x: (x[0], x[1].recall_count), reverse=True)

    top = scored[:top_k]

    # Increment recall_count for retrieved memories
    for _, mem in top:
        await session.execute(
            update(LongTermMemory)
            .where(LongTermMemory.id == mem.id)
            .values(recall_count=LongTermMemory.recall_count + 1)
        )

    return [
        {
            "key": m.memory_key,
            "value": m.memory_value,
            "type": m.memory_type,
            "importance": m.importance,
        }
        for _, m in top
    ]


async def save_memory(
    session: AsyncSession,
    user_id: int,
    memory_type: str,
    value: str,
    importance: int = 5,
    source_session_id: int | None = None,
) -> LongTermMemory:
    """Save or merge a long-term memory entry.

    If a memory with the same key already exists, we merge by updating
    the value (append if different) and bumping the importance.
    """
    key = _make_memory_key(user_id, memory_type, _content_hash(value))

    existing = await session.execute(
        select(LongTermMemory).where(
            LongTermMemory.user_id == user_id,
            LongTermMemory.memory_key == key,
        )
    )
    existing_mem = existing.scalar_one_or_none()

    if existing_mem:
        # Merge: bump importance and append value if it's new
        existing_mem.importance = min(10, existing_mem.importance + 1)
        if value not in existing_mem.memory_value:
            existing_mem.memory_value = f"{existing_mem.memory_value}\n{value}"[:4000]
        return existing_mem

    mem = LongTermMemory(
        user_id=user_id,
        memory_key=key,
        memory_value=value,
        importance=importance,
        source_session_id=source_session_id,
        memory_type=memory_type,
    )
    session.add(mem)
    return mem


async def extract_insights_from_session(
    session: AsyncSession,
    session_id: int,
    user_id: int,
) -> list[dict[str, Any]]:
    """Analyse a completed session and extract key insights as long-term memories.

    This is a lightweight rules-based extractor. For production, this could
    be replaced with an LLM call that analyses the full conversation.
    Returns the list of saved memory dicts.
    """
    result = await session.execute(
        select(PracticeMessage)
        .where(
            PracticeMessage.session_id == session_id,
            PracticeMessage.evaluation.isnot(None),
        )
        .order_by(PracticeMessage.id)
    )
    messages = result.scalars().all()

    saved: list[dict[str, Any]] = []

    for msg in messages:
        evaluation = msg.evaluation or {}
        score = evaluation.get("score", 0)
        feedback = evaluation.get("feedback", "")
        highlights = evaluation.get("highlights", [])
        improvements = evaluation.get("improvements", [])

        # Save strengths (score ≥ 4 messages with highlights)
        if score >= 4 and highlights:
            for h in highlights:
                mem = await save_memory(
                    session, user_id,
                    memory_type="strength",
                    value=str(h),
                    importance=min(10, score + 2),
                    source_session_id=session_id,
                )
                saved.append({"key": mem.memory_key, "value": mem.memory_value, "type": mem.memory_type})

        # Save weaknesses (score ≤ 2 messages with improvements)
        if score <= 2 and improvements:
            for imp in improvements:
                mem = await save_memory(
                    session, user_id,
                    memory_type="weakness",
                    value=str(imp),
                    importance=min(10, (6 - score) + 2),
                    source_session_id=session_id,
                )
                saved.append({"key": mem.memory_key, "value": mem.memory_value, "type": mem.memory_type})

        # Save general insights from feedback
        if feedback and len(feedback) > 20:
            mem = await save_memory(
                session, user_id,
                memory_type="insight",
                value=feedback,
                importance=min(10, score + 1),
                source_session_id=session_id,
            )
            saved.append({"key": mem.memory_key, "value": mem.memory_value, "type": mem.memory_type})

    return saved


def format_memories_for_prompt(memories: list[dict[str, Any]]) -> str:
    """Format retrieved memories as a compact prompt section."""
    if not memories:
        return ""

    lines = ["## 相关长期记忆"]
    for m in memories:
        prefix = {
            "weakness": "⚠️ 薄弱点", "strength": "✅ 优势",
            "insight": "💡 洞察", "preference": "👍 偏好", "pattern": "🔄 模式",
        }.get(m.get("type", ""), "📌")
        lines.append(f"- {prefix}：{m['value']}")
    return "\n".join(lines)
