"""Alembic migration template."""
revision: str = "510b2da09aa8"
down_revision: str | None = "None"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Upgrade to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
